server:
  port: 8004

spring:
  application:
    name: springcloud-provider-hystrix  # 应用名称

eureka:           # 客户端注册到eureka服务中
  client:
    serviceUrl:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/

  instance:
    instance-id: provider-8004    # 自定义服务名称信息
    prefer-ip-address: true       # 访问路径可以显示ip地址
