server:
  port: 9001

spring:
  application:
    name: springcloud-consumer-feign  # 应用名称

eureka:           # 配置访问eureka注册中心
  client:
    serviceUrl:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/

# 开启熔断
feign:
  hystrix:
    enabled: true
