server:
  port: 9000

spring:
  datasource:       # ========= 数据源配置
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:            # MyBatis配置
  mapper-locations: classpath:/mapper/*.xml

pagehelper:         # Pagehelper插件配置
  helper-dialect: mysql             # 数据库方言
  page-size-zero: true              # 设置为true时，如果pageSize=0或者RowBounds.limit = 0就会查询出全部的结果
  reasonable: true                  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  support-methods-arguments: true   # 支持通过Mapper接口参数来传递分页参数
