server:
  port: 7002

spring:
  application:
    name: eureka-center  # 应用名称

eureka:
  instance:
    hostname: eureka02             # eureka服务器的实例名称
  client:
    fetchRegistry: false            # 是否需要从注册中心获取服务列表
    serviceUrl:                     # eureka注册中心地址
      defaultZone: http://eureka01:7001/eureka/,http://eureka03:7003/eureka/